### ISSUE TITLE
😳

### ISSUE THREAD

**Issue by ShaoPengHu** [dingjibang/GDX-RPG#27]
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'GDX-RPG-master'.
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.android.repository.api.RepoManager
	at com.android.builder.sdk.SdkLibData.<init>(SdkLibData.java:34)
	at com.android.builder.sdk.SdkLibData.dontDownload(SdkLibData.java:45)
	at com.android.build.gradle.internal.SdkHandler.<init>(SdkHandler.java:73)
	at com.android.build.gradle.BasePlugin.configureProject(BasePlugin.java:370)
	at com.android.build.gradle.BasePlugin$1.call(BasePlugin.java:338)
	at com.android.build.gradle.BasePlugin$1.call(BasePlugin.java:335)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
	at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:334)
	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:75)

**Comment by ShaoPengHu** [comment]
gradle-4.8.1-bin.zip
